window.POPULOUS_TIME_DATA = {
  "0:00": "0.00",
  "0:05": "0.00",
  "0:10": "0.00",
  "0:15": "0.00",
  "0:20": "0.00",
  "0:25": "0.00",
  "0:30": "0.00",
  "0:35": "0.00",
  "0:40": "0.00",
  "0:45": "0.00",
  "0:50": "0.00",
  "0:55": "0.00",
  "1:00": "0.00",
  "1:05": "0.00",
  "1:10": "0.00",
  "1:15": "0.00",
  "1:20": "0.00",
  "1:25": "0.00",
  "1:30": "0.00",
  "1:35": "0.00",
  "1:40": "0.00",
  "1:45": "0.00",
  "1:50": "0.00",
  "1:55": "0.00",
  "2:00": "0.00",
  "2:05": "0.00",
  "2:10": "0.00",
  "2:15": "0.00",
  "2:20": "0.00",
  "2:25": "0.00",
  "2:30": "0.00",
  "2:35": "0.00",
  "2:40": "0.00",
  "2:45": "0.00",
  "2:50": "0.00",
  "2:55": "0.00",
  "3:00": "0.00",
  "3:05": "0.00",
  "3:10": "0.00",
  "3:15": "0.00",
  "3:20": "0.00",
  "3:25": "0.00",
  "3:30": "0.00",
  "3:35": "0.00",
  "3:40": "0.00",
  "3:45": "0.00",
  "3:50": "0.00",
  "3:55": "0.00",
  "4:00": "0.00",
  "4:05": "0.00",
  "4:10": "0.00",
  "4:15": "0.00",
  "4:20": "0.00",
  "4:25": "0.00",
  "4:30": "0.00",
  "4:35": "0.00",
  "4:40": "0.00",
  "4:45": "0.00",
  "4:50": "0.00",
  "4:55": "0.00",
  "5:00": "0.00",
  "5:05": "0.00",
  "5:10": "0.00",
  "5:15": "0.00",
  "5:20": "0.00",
  "5:25": "0.00",
  "5:30": "0.00",
  "5:35": "0.00",
  "5:40": "0.00",
  "5:45": "0.00",
  "5:50": "0.00",
  "5:55": "0.00",
  "6:00": "0.00",
  "6:05": "0.00",
  "6:10": "0.00",
  "6:15": "0.00",
  "6:20": "0.00",
  "6:25": "0.00",
  "6:30": "0.00",
  "6:35": "0.00",
  "6:40": "0.00",
  "6:45": "0.00",
  "6:50": "0.00",
  "6:55": "0.00",
  "7:00": "0.00",
  "7:05": "0.00",
  "7:10": "0.00",
  "7:15": "0.00",
  "7:20": "0.00",
  "7:25": "0.00",
  "7:30": "0.00",
  "7:35": "0.00",
  "7:40": "0.00",
  "7:45": "0.00",
  "7:50": "0.00",
  "7:55": "0.00",
  "8:00": "0.01",
  "8:05": "0.02",
  "8:10": "0.03",
  "8:15": "0.04",
  "8:20": "0.05",
  "8:25": "0.06",
  "8:30": "0.07",
  "8:35": "0.08",
  "8:40": "0.09",
  "8:45": "0.11",
  "8:50": "0.14",
  "8:55": "0.18",
  "9:00": "0.20",
  "9:05": "0.10",
  "9:10": "0.11",
  "9:15": "0.12",
  "9:20": "0.13",
  "9:25": "0.14",
  "9:30": "0.15",
  "9:35": "0.16",
  "9:40": "0.17",
  "9:45": "0.18",
  "9:50": "0.19",
  "9:55": "0.20",
  "10:00": "0.21",
  "10:05": "0.22",
  "10:10": "0.25",
  "10:15": "0.29",
  "10:20": "0.35",
  "10:25": "0.42",
  "10:30": "0.50",
  "10:35": "0.30",
  "10:40": "0.34",
  "10:45": "0.38",
  "10:50": "0.42",
  "10:55": "0.46",
  "11:00": "0.50",
  "11:05": "0.54",
  "11:10": "0.58",
  "11:15": "0.62",
  "11:20": "0.66",
  "11:25": "0.70",
  "11:30": "0.74",
  "11:35": "0.78",
  "11:40": "0.82",
  "11:45": "0.86",
  "11:50": "0.90",
  "11:55": "0.94",
  "12:00": "0.98",
  "12:05": "1.00",
  "12:10": "1.00",
  "12:15": "1.00",
  "12:20": "1.00",
  "12:25": "1.00",
  "12:30": "1.00",
  "12:35": "1.00",
  "12:40": "1.00",
  "12:45": "1.00",
  "12:50": "1.00",
  "12:55": "1.00",
  "13:00": "1.00",
  "13:05": "1.00",
  "13:10": "1.00",
  "13:15": "1.00",
  "13:20": "1.00",
  "13:25": "1.00",
  "13:30": "1.00",
  "13:35": "0.75",
  "13:40": "0.73",
  "13:45": "0.70",
  "13:50": "0.69",
  "13:55": "0.68",
  "14:00": "0.67",
  "14:05": "0.66",
  "14:10": "0.65",
  "14:15": "0.64",
  "14:20": "0.63",
  "14:25": "0.62",
  "14:30": "0.61",
  "14:35": "0.60",
  "14:40": "0.59",
  "14:45": "0.65",
  "14:50": "0.70",
  "14:55": "0.68",
  "15:00": "0.67",
  "15:05": "0.60",
  "15:10": "0.59",
  "15:15": "0.59",
  "15:20": "0.58",
  "15:25": "0.58",
  "15:30": "0.57",
  "15:35": "0.57",
  "15:40": "0.56",
  "15:45": "0.56",
  "15:50": "0.55",
  "15:55": "0.55",
  "16:00": "0.54",
  "16:05": "0.54",
  "16:10": "0.54",
  "16:15": "0.70",
  "16:20": "0.75",
  "16:25": "0.73",
  "16:30": "0.72",
  "16:35": "0.54",
  "16:40": "0.53",
  "16:45": "0.52",
  "16:50": "0.51",
  "16:55": "0.50",
  "17:00": "0.49",
  "17:05": "0.48",
  "17:10": "0.47",
  "17:15": "0.46",
  "17:20": "0.45",
  "17:25": "0.44",
  "17:30": "0.43",
  "17:35": "0.42",
  "17:40": "0.41",
  "17:45": "0.50",
  "17:50": "0.55",
  "17:55": "0.53",
  "18:00": "0.51",
  "18:05": "0.45",
  "18:10": "0.44",
  "18:15": "0.43",
  "18:20": "0.42",
  "18:25": "0.41",
  "18:30": "0.40",
  "18:35": "0.39",
  "18:40": "0.38",
  "18:45": "0.37",
  "18:50": "0.36",
  "18:55": "0.35",
  "19:00": "0.34",
  "19:05": "0.33",
  "19:10": "0.32",
  "19:15": "0.31",
  "19:20": "0.30",
  "19:25": "0.29",
  "19:30": "0.28",
  "19:35": "0.27",
  "19:40": "0.26",
  "19:45": "0.25",
  "19:50": "0.24",
  "19:55": "0.23",
  "20:00": "0.22",
  "20:05": "0.21",
  "20:10": "0.20",
  "20:15": "0.19",
  "20:20": "0.18",
  "20:25": "0.17",
  "20:30": "0.16",
  "20:35": "0.15",
  "20:40": "0.14",
  "20:45": "0.13",
  "20:50": "0.12",
  "20:55": "0.11",
  "21:00": "0.10",
  "21:05": "0.09",
  "21:10": "0.08",
  "21:15": "0.07",
  "21:20": "0.06",
  "21:25": "0.05",
  "21:30": "0.04",
  "21:35": "0.03",
  "21:40": "0.02",
  "21:45": "0.01",
  "21:50": "0.01",
  "21:55": "0.01",
  "22:00": "0.01",
  "22:05": "0.01",
  "22:10": "0.01",
  "22:15": "0.01",
  "22:20": "0.01",
  "22:25": "0.01",
  "22:30": "0.01",
  "22:35": "0.00",
  "22:40": "0.00",
  "22:45": "0.00",
  "22:50": "0.00",
  "22:55": "0.00",
  "23:00": "0.00",
  "23:05": "0.00",
  "23:10": "0.00",
  "23:15": "0.00",
  "23:20": "0.00",
  "23:25": "0.00",
  "23:30": "0.00",
  "23:35": "0.00",
  "23:40": "0.00",
  "23:45": "0.00",
  "23:50": "0.00",
  "23:55": "0.00"
};

window.LOUNGE_RAW_DATA = [
  {
    "lounge_code": "10001",
    "campus": "인문 캠퍼스",
    "building": "LG-POSCO 경영관",
    "lounge_name": "이명박 라운지",
    "lounge_floor": "2F",
    "infrastructure": "프린터, 복사기",
    "default_type": "오픈형",
    "default_table": "4인 테이블, 1인 소파형 의자 및 테이블",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.8",
    "p_adjusted": "0.943078043",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "0",
    "charge": "1",
    "printer": "1",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "1",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "0",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10002",
    "campus": "인문 캠퍼스",
    "building": "LG-POSCO 경영관",
    "lounge_name": "박현주 라운지",
    "lounge_floor": "4F",
    "infrastructure": "정수기",
    "default_type": "룸형",
    "default_table": "2인 테이블, 벽면 소파와 1인 의자 및 테이블",
    "usage_time": "90",
    "change_p": "0.962223837",
    "default_populous": "0.6",
    "p_adjusted": "0.964112645",
    "default_noise": "30",
    "noise level": "1",
    "alone": "1",
    "two": "1",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "1",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "0",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10003",
    "campus": "인문 캠퍼스",
    "building": "LG-POSCO 경영관",
    "lounge_name": "SUPEX홀 옆 라운지",
    "lounge_floor": "4F",
    "infrastructure": "정수기",
    "default_type": "오픈형",
    "default_table": "4인 테이블, 1인 소파형 의자 및 테이블",
    "usage_time": "35",
    "change_p": "0.905723664",
    "default_populous": "0.4",
    "p_adjusted": "0.901009847",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "1",
    "charge": "0",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "0",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10004",
    "campus": "인문 캠퍼스",
    "building": "현대자동차경영관",
    "lounge_name": "B3 라운지",
    "lounge_floor": "B3",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "4인 사각 테이블, 1인 소파형 의자 및 테이블",
    "usage_time": "45",
    "change_p": "0.925874712",
    "default_populous": "0.6",
    "p_adjusted": "0.929580977",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "37",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10005",
    "campus": "인문 캠퍼스",
    "building": "현대자동차경영관",
    "lounge_name": "B1 라운지",
    "lounge_floor": "B1",
    "infrastructure": "편의점, 카페",
    "default_type": "오픈형",
    "default_table": "4인 테이블, 1인 소파형 의자 및 테이블, 다인용 소파형 의자 및 테이블",
    "usage_time": "70",
    "change_p": "0.951695153",
    "default_populous": "0.6",
    "p_adjusted": "0.954110395",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "1",
    "bank": "0",
    "shower": "0",
    "distance": "37",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10006",
    "campus": "인문 캠퍼스",
    "building": "현대자동차경영관",
    "lounge_name": "계단 라운지",
    "lounge_floor": "1F",
    "infrastructure": "",
    "default_type": "계단형",
    "default_table": "계단형",
    "usage_time": "20",
    "change_p": "0.840896415",
    "default_populous": "0.5",
    "p_adjusted": "0.840896415",
    "default_noise": "60",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "0",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "37",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10007",
    "campus": "인문 캠퍼스",
    "building": "현대자동차경영관",
    "lounge_name": "2층 라운지",
    "lounge_floor": "2F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "4인 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.5",
    "p_adjusted": "0.943874313",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "0",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "0",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "37",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10008",
    "campus": "인문 캠퍼스",
    "building": "현대자동차경영관",
    "lounge_name": "MBA 라운지",
    "lounge_floor": "4F",
    "infrastructure": "정수기",
    "default_type": "오픈형",
    "default_table": "4인 사각 테이블, 1인 소파형 의자 및 테이블",
    "usage_time": "65",
    "change_p": "0.948077514",
    "default_populous": "0.5",
    "p_adjusted": "0.948077514",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "1",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "37",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10009",
    "campus": "인문 캠퍼스",
    "building": "현대자동차경영관",
    "lounge_name": "장치평 라운지",
    "lounge_floor": "4F",
    "infrastructure": "정수기",
    "default_type": "오픈형",
    "default_table": "4인 사각 테이블, 1인 소파형 의자 및 테이블",
    "usage_time": "45",
    "change_p": "0.925874712",
    "default_populous": "0.5",
    "p_adjusted": "0.925874712",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "1",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "37",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10010",
    "campus": "인문 캠퍼스",
    "building": "운초우선교육관",
    "lounge_name": "라운지 1-1",
    "lounge_floor": "1F",
    "infrastructure": "편의점, 카페, 도서반납기, 정수기",
    "default_type": "오픈형",
    "default_table": "4인 사각 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.5",
    "p_adjusted": "0.943874313",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "0",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "1",
    "cafe": "1",
    "copier": "0",
    "convenience": "1",
    "bank": "0",
    "shower": "0",
    "distance": "258",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10011",
    "campus": "인문 캠퍼스",
    "building": "운초우선교육관",
    "lounge_name": "400라운지",
    "lounge_floor": "4F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "4인 사각 테이블",
    "usage_time": "55",
    "change_p": "0.938930911",
    "default_populous": "0.5",
    "p_adjusted": "0.938930911",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "0",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "258",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10012",
    "campus": "인문 캠퍼스",
    "building": "중앙광장 지하",
    "lounge_name": "CCL",
    "lounge_floor": "B1",
    "infrastructure": "카페, 식당, 은행, 편의점",
    "default_type": "룸형",
    "default_table": "소파형 개인석, 1인 의자 및 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.8",
    "p_adjusted": "0.952293166",
    "default_noise": "30",
    "noise level": "1",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "1",
    "bank": "1",
    "shower": "0",
    "distance": "222",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10013",
    "campus": "인문 캠퍼스",
    "building": "중앙광장 지하",
    "lounge_name": "B1-2 라운지",
    "lounge_floor": "B1",
    "infrastructure": "카페, 식당, 은행, 편의점",
    "default_type": "룸형",
    "default_table": "1인 의자 및 테이블, 1인 소파",
    "usage_time": "15",
    "change_p": "0.793700526",
    "default_populous": "0.8",
    "p_adjusted": "0.824645447",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "0",
    "charge": "0",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "1",
    "bank": "1",
    "shower": "0",
    "distance": "222",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10014",
    "campus": "인문 캠퍼스",
    "building": "중앙광장 지하",
    "lounge_name": "하나은행 라운지",
    "lounge_floor": "B1",
    "infrastructure": "카페, 식당, 은행, 편의점",
    "default_type": "룸형",
    "default_table": "소파형 개인석, 침대형 자리",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.8",
    "p_adjusted": "0.952293166",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "1",
    "bank": "1",
    "shower": "0",
    "distance": "222",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10015",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "라운지 B1-1",
    "lounge_floor": "B1",
    "infrastructure": "샤워실",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블, 8인 의자 및 사각 테이블, 소파형 좌석, 칸막이 좌석",
    "usage_time": "45",
    "change_p": "0.925874712",
    "default_populous": "0.9",
    "p_adjusted": "0.94069977",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "1",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "1",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "1",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10016",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "라운지 B1-2",
    "lounge_floor": "B1",
    "infrastructure": "샤워실",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블, 8인 의자 및 사각 테이블, 소파형 좌석, 칸막이 좌석",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.9",
    "p_adjusted": "0.946426393",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "1",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "1",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "1",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10017",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블, 8인 의자 및 사각 테이블, 소파형 좌석, 칸막이 좌석",
    "usage_time": "35",
    "change_p": "0.905723664",
    "default_populous": "0.9",
    "p_adjusted": "0.924578931",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "1",
    "white_noise": "1",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "1",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10018",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "라운지 2-1",
    "lounge_floor": "2F",
    "infrastructure": "정수기",
    "default_type": "오픈형",
    "default_table": "4인 소파형 좌석 및 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.9",
    "p_adjusted": "0.95509945",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "1",
    "individual": "0",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10019",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "309 로비라운지",
    "lounge_floor": "3F",
    "infrastructure": "카페",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블",
    "usage_time": "35",
    "change_p": "0.905723664",
    "default_populous": "0.9",
    "p_adjusted": "0.924578931",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "0",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10020",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "라운지 3-1",
    "lounge_floor": "3F",
    "infrastructure": "카페",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블, 원형 1인용 소파",
    "usage_time": "25",
    "change_p": "0.870550563",
    "default_populous": "0.9",
    "p_adjusted": "0.896440451",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10021",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "계단 라운지",
    "lounge_floor": "3F",
    "infrastructure": "카페",
    "default_type": "계단형",
    "default_table": "계단형",
    "usage_time": "10",
    "change_p": "0.707106781",
    "default_populous": "0.9",
    "p_adjusted": "0.765685425",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "0",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "1",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "1",
    "charge": "0",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10022",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "라운지 3-2",
    "lounge_floor": "3F",
    "infrastructure": "카페",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블, 원형 1인용 소파",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.9",
    "p_adjusted": "0.946426393",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10023",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "라운지 3-3",
    "lounge_floor": "3F",
    "infrastructure": "카페",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블, 원형 1인용 소파",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.9",
    "p_adjusted": "0.95509945",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10024",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "라운지 3-4",
    "lounge_floor": "3F",
    "infrastructure": "카페",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블, 원형 1인용 소파",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.9",
    "p_adjusted": "0.95509945",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10025",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "라운지 4-2",
    "lounge_floor": "4F",
    "infrastructure": "정수기, 자판기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.9",
    "p_adjusted": "0.946426393",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "0",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10026",
    "campus": "인문 캠퍼스",
    "building": "SK미래관",
    "lounge_name": "라운지 4-3",
    "lounge_floor": "4F",
    "infrastructure": "정수기, 자판기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블",
    "usage_time": "55",
    "change_p": "0.938930911",
    "default_populous": "0.9",
    "p_adjusted": "0.951144729",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "0",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "423",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10027",
    "campus": "인문 캠퍼스",
    "building": "미디어관",
    "lounge_name": "동원 라운지",
    "lounge_floor": "1F",
    "infrastructure": "프린터, 정수기, 도서반납기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블, 창가 테이블석",
    "usage_time": "70",
    "change_p": "0.951695153",
    "default_populous": "0.8",
    "p_adjusted": "0.95894088",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "0",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "1",
    "water": "1",
    "book_dispenser": "1",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "820",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10028",
    "campus": "인문 캠퍼스",
    "building": "미디어관",
    "lounge_name": "아리카페 라운지",
    "lounge_floor": "1F",
    "infrastructure": "프린터, 정수기, 도서반납기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블, 대형 책상",
    "usage_time": "55",
    "change_p": "0.938930911",
    "default_populous": "0.8",
    "p_adjusted": "0.948091274",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "0",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "1",
    "water": "1",
    "book_dispenser": "1",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "820",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10029",
    "campus": "인문 캠퍼스",
    "building": "미디어관",
    "lounge_name": "308라운지",
    "lounge_floor": "3F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.8",
    "p_adjusted": "0.952293166",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "1",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "820",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10030",
    "campus": "인문 캠퍼스",
    "building": "4.18기념관",
    "lounge_name": "김정호 플로어",
    "lounge_floor": "4F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.9",
    "p_adjusted": "0.946426393",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "1",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "607",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10031",
    "campus": "인문 캠퍼스",
    "building": "한투스퀘어",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "카페, 정수기, 식당",
    "default_type": "오픈형",
    "default_table": "4인 의자 및 사각 테이블",
    "usage_time": "20",
    "change_p": "0.840896415",
    "default_populous": "1",
    "p_adjusted": "0.880672311",
    "default_noise": "70",
    "noise level": "3",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "0",
    "multi": "1",
    "eat": "1",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "0",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "640",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10032",
    "campus": "인문 캠퍼스",
    "building": "타이거프라자",
    "lounge_name": "301 라운지",
    "lounge_floor": "3F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블",
    "usage_time": "45",
    "change_p": "0.925874712",
    "default_populous": "0.6",
    "p_adjusted": "0.929580977",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "862",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10033",
    "campus": "인문 캠퍼스",
    "building": "타이거프라자",
    "lounge_name": "302B 라운지",
    "lounge_floor": "3F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블",
    "usage_time": "35",
    "change_p": "0.905723664",
    "default_populous": "0.6",
    "p_adjusted": "0.910437481",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "862",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10034",
    "campus": "인문 캠퍼스",
    "building": "타이거프라자",
    "lounge_name": "401 라운지",
    "lounge_floor": "4F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블",
    "usage_time": "40",
    "change_p": "0.917004043",
    "default_populous": "0.6",
    "p_adjusted": "0.921153841",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "1",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "862",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10035",
    "campus": "인문 캠퍼스",
    "building": "타이거프라자",
    "lounge_name": "401A 라운지",
    "lounge_floor": "4F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 원형 테이블",
    "usage_time": "40",
    "change_p": "0.917004043",
    "default_populous": "0.6",
    "p_adjusted": "0.921153841",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "1",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "862",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10036",
    "campus": "인문 캠퍼스",
    "building": "우당교양관",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.9",
    "p_adjusted": "0.95509945",
    "default_noise": "60",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "0",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "727",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10037",
    "campus": "인문 캠퍼스",
    "building": "동원글로벌리더십홀",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "4인 의자 및 사각 테이블",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.6",
    "p_adjusted": "0.936381342",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "0",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "431",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20001",
    "campus": "과학 캠퍼스",
    "building": "우정정보관",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "자판기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블, 창가 테이블석",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.6",
    "p_adjusted": "0.946680597",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1285",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20002",
    "campus": "과학 캠퍼스",
    "building": "정운오IT교양관",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "샤워실",
    "default_type": "오픈형",
    "default_table": "4인 소파형 좌석 및 테이블",
    "usage_time": "20",
    "change_p": "0.840896415",
    "default_populous": "0.6",
    "p_adjusted": "0.848851594",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "1",
    "dark": "0",
    "individual": "0",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "1",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "1",
    "distance": "1310",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20003",
    "campus": "과학 캠퍼스",
    "building": "정운오IT교양관",
    "lounge_name": "2층 라운지",
    "lounge_floor": "2F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.6",
    "p_adjusted": "0.946680597",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1310",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20004",
    "campus": "과학 캠퍼스",
    "building": "정운오IT교양관",
    "lounge_name": "3층 라운지",
    "lounge_floor": "3F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "70",
    "change_p": "0.951695153",
    "default_populous": "0.6",
    "p_adjusted": "0.954110395",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "1",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1310",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20005",
    "campus": "과학 캠퍼스",
    "building": "정운오IT교양관",
    "lounge_name": "4층 라운지",
    "lounge_floor": "4F",
    "infrastructure": "정수기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "40",
    "change_p": "0.917004043",
    "default_populous": "0.6",
    "p_adjusted": "0.921153841",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "1",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1310",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20006",
    "campus": "과학 캠퍼스",
    "building": "생명과학대학서관",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "정수기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "45",
    "change_p": "0.925874712",
    "default_populous": "0.6",
    "p_adjusted": "0.929580977",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1448",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20007",
    "campus": "과학 캠퍼스",
    "building": "생명과학대학서관",
    "lounge_name": "2층 라운지",
    "lounge_floor": "2F",
    "infrastructure": "정수기, 프린터, 자판기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.6",
    "p_adjusted": "0.936381342",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "1",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1448",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20008",
    "campus": "과학 캠퍼스",
    "building": "로봇융합관",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "45",
    "change_p": "0.925874712",
    "default_populous": "0.6",
    "p_adjusted": "0.929580977",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1903",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20009",
    "campus": "과학 캠퍼스",
    "building": "로봇융합관",
    "lounge_name": "2층 라운지",
    "lounge_floor": "2F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.6",
    "p_adjusted": "0.946680597",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "1",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1903",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20010",
    "campus": "과학 캠퍼스",
    "building": "로봇융합관",
    "lounge_name": "3층 라운지",
    "lounge_floor": "3F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "35",
    "change_p": "0.905723664",
    "default_populous": "0.6",
    "p_adjusted": "0.910437481",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "1",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1903",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20011",
    "campus": "과학 캠퍼스",
    "building": "로봇융합관",
    "lounge_name": "4층 라운지",
    "lounge_floor": "4F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.6",
    "p_adjusted": "0.946680597",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1903",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20012",
    "campus": "과학 캠퍼스",
    "building": "신공학관",
    "lounge_name": "라운지 2-1",
    "lounge_floor": "1F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "4인 테이블, 1인 소파형 의자 및 테이블, 다인용 소파형 의자 및 테이블",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.6",
    "p_adjusted": "0.936381342",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1908",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20013",
    "campus": "과학 캠퍼스",
    "building": "신공학관",
    "lounge_name": "라운지 2-1",
    "lounge_floor": "1F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "4인 테이블, 1인 소파형 의자 및 테이블, 다인용 소파형 의자 및 테이블",
    "usage_time": "40",
    "change_p": "0.917004043",
    "default_populous": "0.6",
    "p_adjusted": "0.921153841",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1908",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20014",
    "campus": "과학 캠퍼스",
    "building": "신공학관",
    "lounge_name": "라운지 3-1",
    "lounge_floor": "3F",
    "infrastructure": "자판기",
    "default_type": "오픈형",
    "default_table": "4인 테이블, 1인 소파형 의자 및 테이블, 다인용 소파형 의자 및 테이블",
    "usage_time": "45",
    "change_p": "0.925874712",
    "default_populous": "0.6",
    "p_adjusted": "0.929580977",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1908",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20015",
    "campus": "과학 캠퍼스",
    "building": "창의관",
    "lounge_name": "라운지 1-1",
    "lounge_floor": "1F",
    "infrastructure": "은행",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "60",
    "change_p": "0.943874313",
    "default_populous": "0.6",
    "p_adjusted": "0.946680597",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "1",
    "shower": "0",
    "distance": "1850",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20016",
    "campus": "과학 캠퍼스",
    "building": "창의관",
    "lounge_name": "라운지 1-2",
    "lounge_floor": "1F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "75",
    "change_p": "0.954841604",
    "default_populous": "0.6",
    "p_adjusted": "0.957099524",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1850",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20017",
    "campus": "과학 캠퍼스",
    "building": "공학관",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.6",
    "p_adjusted": "0.936381342",
    "default_noise": "60",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1808",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20018",
    "campus": "과학 캠퍼스",
    "building": "아산이학관",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "자판기, 프린터, 도서반납기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.6",
    "p_adjusted": "0.936381342",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "1",
    "water": "0",
    "book_dispenser": "1",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1681",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20019",
    "campus": "과학 캠퍼스",
    "building": "하나과학관",
    "lounge_name": "생명과학인의 숲 라운지",
    "lounge_floor": "1F",
    "infrastructure": "정수기, 자판기",
    "default_type": "오픈형",
    "default_table": "소파, 1인 의자 및 원형 테이블, 1인 소파형 의자 및 원형 테이블",
    "usage_time": "30",
    "change_p": "0.890898718",
    "default_populous": "0.6",
    "p_adjusted": "0.896353782",
    "default_noise": "50",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "1",
    "hard_chair": "0",
    "sofa": "1",
    "lie": "1",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1643",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20020",
    "campus": "과학 캠퍼스",
    "building": "메디힐지구환경관",
    "lounge_name": "1층 라운지",
    "lounge_floor": "1F",
    "infrastructure": "정수기",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "50",
    "change_p": "0.933032992",
    "default_populous": "0.6",
    "p_adjusted": "0.936381342",
    "default_noise": "40",
    "noise level": "1",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1643",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "20021",
    "campus": "과학 캠퍼스",
    "building": "메디힐지구환경관",
    "lounge_name": "2층 라운지",
    "lounge_floor": "2F",
    "infrastructure": "",
    "default_type": "오픈형",
    "default_table": "1인 의자 및 사각 테이블",
    "usage_time": "55",
    "change_p": "0.938930911",
    "default_populous": "0.6",
    "p_adjusted": "0.941984365",
    "default_noise": "60",
    "noise level": "2",
    "alone": "1",
    "two": "0",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1643",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "FALSE",
    "sun": "FALSE"
  },
  {
    "lounge_code": "10038",
    "campus": "인문 캠퍼스",
    "building": "LG-POSCO 경영관",
    "lounge_name": "지하 1층 라운지",
    "lounge_floor": "B1",
    "infrastructure": "정수기, ATM",
    "default_type": "오픈형",
    "default_table": "4인 원형 테이블",
    "usage_time": "20",
    "change_p": "0.840896415",
    "default_populous": "0.6",
    "p_adjusted": "0.848851594",
    "default_noise": "45",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "0",
    "multi": "1",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "0",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "1",
    "shower": "0",
    "distance": "0",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10039",
    "campus": "인문 캠퍼스",
    "building": "백주년기념삼성관",
    "lounge_name": "지하 1층 라운지",
    "lounge_floor": "B1",
    "infrastructure": "정수기",
    "default_type": "오픈형",
    "default_table": "2인 테이블",
    "usage_time": "15",
    "change_p": "0.793700526",
    "default_populous": "0.6",
    "p_adjusted": "0.8040155",
    "default_noise": "55",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "0",
    "dark": "0",
    "individual": "0",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "0",
    "lie": "0",
    "charge": "0",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "96",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "10040",
    "campus": "인문 캠퍼스",
    "building": "현대자동차경영관",
    "lounge_name": "5층 계단형 라운지",
    "lounge_floor": "5F",
    "infrastructure": "",
    "default_type": "계단형",
    "default_table": "계단형, 빈백",
    "usage_time": "40",
    "change_p": "0.917004043",
    "default_populous": "0.6",
    "p_adjusted": "0.921153841",
    "default_noise": "35",
    "noise level": "1",
    "alone": "1",
    "two": "1",
    "threefour": "0",
    "fiveormore": "0",
    "white_noise": "0",
    "bright": "1",
    "dark": "0",
    "individual": "1",
    "multi": "0",
    "eat": "0",
    "partition": "0",
    "high_table": "0",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "1",
    "charge": "0",
    "printer": "0",
    "water": "0",
    "book_dispenser": "0",
    "cafe": "0",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "37",
    "open": "8:30",
    "close": "22:30",
    "mon": "TRUE",
    "tue": "TRUE",
    "wed": "TRUE",
    "thu": "TRUE",
    "fri": "TRUE",
    "sat": "TRUE",
    "sun": "TRUE"
  },
  {
    "lounge_code": "20022",
    "campus": "과학 캠퍼스",
    "building": "하나스퀘어",
    "lounge_name": "지하 1층 라운지",
    "lounge_floor": "B1",
    "infrastructure": "정수기, 식당, 카페",
    "default_type": "룸형",
    "default_table": "1인 의자 및 사각 테이블, 원형 테이블, 벽면 소파, 소파, 4인용 소파 및 테이블석",
    "usage_time": "30",
    "change_p": "0.890898718",
    "default_populous": "0.9",
    "p_adjusted": "0.912718975",
    "default_noise": "60",
    "noise level": "2",
    "alone": "1",
    "two": "1",
    "threefour": "1",
    "fiveormore": "0",
    "white_noise": "1",
    "bright": "0",
    "dark": "0",
    "individual": "0",
    "multi": "1",
    "eat": "1",
    "partition": "0",
    "high_table": "1",
    "low_table": "0",
    "hard_chair": "1",
    "sofa": "1",
    "lie": "0",
    "charge": "1",
    "printer": "0",
    "water": "1",
    "book_dispenser": "0",
    "cafe": "1",
    "copier": "0",
    "convenience": "0",
    "bank": "0",
    "shower": "0",
    "distance": "1555",
    "open": "",
    "close": "",
    "mon": "",
    "tue": "",
    "wed": "",
    "thu": "",
    "fri": "",
    "sat": "",
    "sun": ""
  }
];
